//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticaret2022.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<long> UrunFiyat { get; set; }
    }
}
